config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :steps, only: [:new, :index, :show, :update]
  root 'steps#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  # validates :age, numericality: true

  # validate :add_errors
  #   def add_errors
  #     if email.blank?
  #       errors[:base] << "メールアドレスを入力してください"
  #     end

  #     unless email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #       errors[:base] << "適切なメールアドレスを入力してください"
  #     end

  #     if name.length > 255
  #       errors[:base] << "メールアドレスは255文字以内で入力してください"
  #     end
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  include Wicked::Wizard
  steps :second, :thanks, :thanks2

  def new
    @user = User.new
    render "new"
  end

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.attributes = user_params
    render_wizard @user
  end

  private

  def finish_wizard_path
    steps_thanks_path
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_params
    params.require(:user).permit(:purpose, :level, :name, :phone_number, :season, :email, :preference, :age, :area_preference, :school_level, :school_type, :school_scale, :japnum)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :basic_auth, only: [:index, :show, :edit, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all.order('id DESC')
    # render :layout => 'users'
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      NotificationMailer.notice(@user).deliver_now
      redirect_to steps_path
    else
      render "steps/new"
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV['ADMIN_LOGIN_NAME'] && password == ENV['ADMIN_LOGIN_PASSWORD']
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:purpose, :level, :name, :phone_number, :season, :email, :preference, :age, :area_preference, :school_level, :school_type, :school_scale, :japnum)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_body.html.erb
<!-- ====================campaign==================== -->

  <div id="campaign" style="background-image:url(<%= asset_path "campaign.png" %>)">
    <div class="white-bored">
      <div class="camp-bg">
      <h2>今だけお得な<br class="d-sm-none">キャンペーン実施中</h2>
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="camp-part">
                <p class="camp_first">★キャンペーンA：ともだちを紹介して、最大30,000円キャッシュバック!!</p>
                <p class="camp-second">紹介頂いたご友人が弊社で留学参加を申し込んだ場合、紹介者とご友人両方にキャッシュバックを致します。</p>
                <p class="camp-second">※ご友人の留学期間に応じて、4週間毎に5000円のキャッシュバックになります。</p>
                <br>
                <p class="camp_first">★キャンペーンB：
                個別面談に参加で留学費用から5,000円OFF!!</p>
                <p class="camp-second">無料留学面談にお越し頂いた方全員に5,000円OFFの割引を実施致します。</p>
                <br>
                <p class="camp-second">＜注意＞<br>※キャンペーンAとBは併用可能です。<br>※本キャンペーンは予告なく終了する場合がございますのでご了承ください。<br>※どちらも留学期間が4週間以上で適用になります。 </p>
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- ====================riyu==================== -->

<div id="riyu">
  <h2>HANASERUが<br class="d-sm-none">選ばれる理由</h2>
  <h6>徹底的にお客様に寄り添います。</h6>
  <div class="part">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          <div class="strength">
            <p class="strength-a">1.「手数料完全無料！」</p>
            <p class="strength-b">費用を抑えれてお得</p>
            <!-- <img src="img/investment.png" alt="..."> -->
            <%= image_tag('riyu1.png') %>
            <br>
            <p class="strength-c">HANASERUでは、一切の手数料をお客様から頂いておらず完全無料でご利用頂けます。そして各種割引で学校に直接お申し込みされるより、費用を抑えてお安く留学が可能です。</p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="strength">
            <p class="strength-a">2.「納得いくまで何度でも！」</p>
            <p class="strength-b">手厚い留学相談</p>
            <!-- <img src="img/consulting.png" alt="..."> -->
            <%= image_tag('riyu2.png') %>
            <br>
            <p class="strength-c">納得いくまで何度でも無料のカウンセリング。お忙しい方でも便利なスカイプ・オンライン面談。LINE@での24時間チャットで気軽に質問も可能です。留学前後の勉強サポートも好評です。</p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="strength" style="padding-bottom: 0px;">
            <p class="strength-a">3.「留学中も安心安全！」</p>
            <p class="strength-b">サポート体制も充実</p>
            <!-- <img src="img/support.png" alt="..."> -->
            <%= image_tag('riyu3.png') %>
            <br>
            <p class="strength-c">現地在住の日本人スタッフが万一の際にも手厚くサポート。24時間チャットサポートで緊急時も安心です。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal-link">
  <a class="btn btn-danger badge-pill" onclick="gtag('event', 'click', {'event_category': 'inquiry','event_label': 'middle1'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#top" role="button">無料でおすすめの学校を診断</a>
</div>

<!-- ====================counsellor==================== -->

<div id="counseller">
  <div class="part">
    <div class="frame">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="counseller-info">
            <h3>フィリピン留学のプロが<br class="d-sm-none">徹底相談</h3>
            <div class="counseller-img c-img-small"">
              <!-- <img src="img/nonaka90.jpg" alt="..."> -->
              <%= image_tag('counsellor.jpg', :class => "") %>
            </div>
            <p>留学でお客様の人生を広げるお手伝いをさせてください！フィリピン最大のポータルサイトの元運営メンバーだからこそ知っている、フィリピン留学、バギオ留学のメリット・デメリットを余すことなくお伝えできればと思います。バギオで英語を勉強して終わりではなく、留学をしてどういうキャリアを作るか、どんな人生を築いていくかを一緒に考えさせてください。</p>
            <div class="middle-link">
              <a class="btn btn-success badge-pill big-link" onclick="gtag('event', 'click', {'event_category': 'line','event_label': 'middle'});" onclick="return gtag_report_conversion('http://line.me/ti/p/%40ukz1853u')" href="http://line.me/ti/p/%40ukz1853u" role="button" target="_blank">LINEで相談する</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="counseller-img c-img-big">
            <%= image_tag('counsellor.jpg') %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

<!-- ====================event==================== -->

<div id="event" style="background-image:url(<%= asset_path "event.jpg" %>)">
  <div class="transparent-event">
  <h2>無料留学相談会実施中!!</h2>
  <div class="part">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
          <ul class="event-info">
            <li>○ 東京・神奈川で毎日開催</li>
            <li>○ 出張面談も承ります</li>
            <li>○ 遠方の方もSkypeでオンライン面談可能</li>
            <li>○ 24時間LINE＠チャット対応</li>
          </ul>
        </div>
        <div class="col-md-5">
          <div class="schedule">
            <h3>＜当日の流れ＞</h3>
            <p><span class="nagare">STEP1</span>フィリピン留学のリアル</p>
            <p><span class="nagare">STEP2</span>留学プランと学校選び</p>
            <p><span class="nagare">STEP3</span>留学費用お見積もり</p>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
<!--     <div class="middle-link">
      <a class="btn btn-danger badge-pill -linkbig" onclick="gtag('event', 'click', {'event_category': 'contact','event_label': 'event'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#contact" role="button">無料で面談予約</a>
    </div> -->
  </div>
  </div>
</div>

<!-- ====================miryoku==================== -->

<div id="miryoku">
  <h2>フィリピン留学の魅力</h2>
  <h6>最適な英語学習の環境で世界を広げるチャンスがそこにあります。</h6>
  <div class="part">
    <div class="container-fluid">
      <div class="row">
        <!-- <div class="col-md-1 d-none d-sm-block"></div> -->
        <div class="col-md-12">
          <div class="card-deck">
            <div class="card">
              <!-- <img class="card-img-top" src="img/coins-1726618_640_169.jpg" alt="カード1の画像"> -->
              <%= image_tag('miryoku1.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">1. 欧米の半額以下!? 圧倒的な安さ</h5>
                <p class="card-text">平均１ヶ月の授業料は15万円ほど、その授業料には寮の宿泊費用と三食の費用が基本的には含まれているので日常のお小遣いや航空券を足しても総額20万円ほどで留学可能。トータルで比較すると、欧米やオーストラリアなどの留学費用の半額以下で留学ができるのが大きな魅力です。</p>
              </div>
            </div>
            <div class="card">
              <!-- <img class="card-img-top" src="img/DSC06701_169.jpg" alt="カード2の画像"> -->
              <%= image_tag('miryoku2.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">2. 完全マンツーマン授業</h5>
                <p class="card-text">語学留学では10~20人の集団授業がメインですが、中々発言できずに英語が伸びないなんてこともしばしば。フィリピン留学ではマンツーマン授業が主体であなたのレベルに合わせた最適な授業で確実に英語を伸ばせます！</p>
              </div>
            </div>
            <div class="card">
              <!-- <img class="card-img-top" src="img/cardillera_600_80.jpg" alt="カード3の画像"> -->
              <%= image_tag('miryoku3.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">3. 治安も安心な学園都市</h5>
                <p class="card-text">少し不安な治安についても、学園都市バギオの犯罪率は東京以下というデータもあるくらい治安が良く安心して学習に集中できます。また物価も日本の1/3ほどなのでリーズナブルに生活可能です。平日はしっかり勉強して週末はリフレッシュでメリハリのきいた最高のフィリピンステイを送りましょう。</p>
              </div>
            </div>
          </div>
        </div>
        <!-- <div class="col-md-1 d-none d-sm-block"></div> -->
      </div>
    </div>
  </div>

  <div class="modal-link">
    <a class="btn btn-danger badge-pill" onclick="gtag('event', 'click', {'event_category': 'inquiry','event_label': 'middle2'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#top" role="button">無料でおすすめの学校を診断</a>
  </div>

</div>

<!-- ====================support==================== -->

<div id="support">
  <h2>充実のサポート内容</h2>
  <h6>安心して出発でき、最高の留学生活を送れるよう全力でサポート致します。</h6>
  <div class="part">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th>留学前</th>
                <td>○ 納得いくまで何度でも無料のカウンセリング<br>○ 英語初心者でも安心の学習サポート<br>○ 航空券購入・保険のサポート<br>○ 学校入学手続き<br>○ LINE@での24時間チャット<br>○ 地方でも安心のスカイプ面談</td>
              </tr>
              <tr>
                <th>留学中</th>
                <td>○ 緊急時の現地スタッフ対応<br>○ 安心の24時間チャットサポート<br>○ 留学中のボランティア参加など</td>
              </tr>
              <tr>
                <th>帰国後</th>
                <td>○ ワーホリサポート<br>○ 転職支援・紹介<br>○ 新卒就活サポート<br>○ フィリピンNGOインターン紹介</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</div>

<!-- <div class="modal-link">
  <a class="btn btn-danger badge-pill" onclick="gtag('event', 'click', {'event_category': 'contact','event_label': 'navbar'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#top" role="button">無料でおすすめの学校を診断</a>
</div> -->

<!-- ====================voice==================== -->

<div id="voice">
  <h2>お客様の声</h2>
  <h6>様々なご年齢・職業の方から評価を頂いております。</h6>
  <div class="part">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card-deck">
            <div class="card">
              <%= image_tag('student1.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">"デメリットも伝えてくれて信頼できた"</h5>
                <p class="card-text">慣れない海外で全てが不安でしたが、何度も無料で面談をしてくれ、親身に相談に乗って頂き、学校毎にメリットだけでなく、デメリットも教えてくれて凄く参考になりました。また英語初心者の私に学校選びだけでなく勉強方法のアドバイスまでしてくれたのが他のエージェントと比べて印象的でした。</p>
              </div>
            </div>
            <div class="card">
              <%= image_tag('student2.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">"留学中も親切でNGOに繋げてくれた"</h5>
                <p class="card-text">留学が決定したら終わりではなく、留学中に学校のスタッフに相談しずらいこともLINEでいつでも相談に乗って頂いたのが非常に助かりました。また個人的にせっかくフィリピンに来たのだからボランティアなどで現地を知りたいと思い、相談したところNGOを紹介してくれるなど、最高の留学にすることができました。</p>
              </div>
            </div>
            <div class="card">
              <%= image_tag('student3.jpg', :class => "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title">"バギオにハマってリピートです"</h5>
                <p class="card-text">留学出発後、帰国後ともによく連絡を頂き、送り出してすぐ終わりじゃない姿勢に好感を持てました。また2回目の留学もバギオに来てしまうくらいバギオの雰囲気にハマってしまいました。リピート割引もあって、継続して学習するモチベーションになっています！</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- ====================footer==================== -->

<footer>
  <div class="modal-link">
    <a class="btn btn-danger badge-pill" onclick="gtag('event', 'click', {'event_category': 'inquiry','event_label': 'middle3'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#top" role="button">無料でおすすめの学校を診断</a>
  </div>
  <!-- <div class="footer-content">
    <div class="footer-link">
      <a class="btn btn-danger badge-pill" onclick="gtag('event', 'click', {'event_category': 'contact','event_label': 'navbar'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#top" role="button">無料でおすすめの学校を診断</a>
    </div> -->
    <!-- <div class="footer-link">
      <a class="btn btn-success badge-pill" onclick="gtag('event', 'click', {'event_category': 'line','event_label': 'navbar'});" onclick="return gtag_report_conversion('http://line.me/ti/p/%40ukz1853u')" href="http://line.me/ti/p/%40ukz1853u" role="button" target="_blank">LINEで気軽に相談する</a>
    </div> -->
    <!-- <div class="company-link">
      <a href="https://connect-flow.me/" target="_blank">運営会社</a>
    </div> -->
  </div>
  <p>Copyright &copy 2018 <a href="https://connect-flow.me/" target="_blank">Connect&Flow inc,</a> All Rights Reserved.</p>
</footer>

app/views/layouts/_head.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121914020-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-121914020-1');
gtag('config', 'AW-797869593');
</script>

<!-- Google Adwordsのスニペット -->
<!-- Event snippet for submit conversion page
In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
<script>
    function gtag_report_conversion(url) {
    var callback = function () {
      if (typeof(url) != 'undefined') {
        window.location = url;
      }
    };
    gtag('event', 'conversion', {
        'send_to': 'AW-797869593/c2E8CJy7gYYBEJmMuvwC',
        'event_callback': callback
    });
    return false;
    }
</script>



<!-- //OGP共通項目 -->
<meta property="og:title" content="人生を変えるフィリピン留学" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://ryugaku.connect-flow.me/" />
<meta property="og:image" content="http://ryugaku.connect-flow.me/img/hanaseru_ogp_1200.jp" />
<meta property="og:site_name"  content="HANASERU" />
<meta property="og:description" content="人生を変えるフィリピン留学。完全無料の留学エージェント「HANASERU」" />

<!-- //Facebook用 -->
<!-- <meta property="fb:app_id" content="214709949332456" /> -->
<!-- <meta property="article:publisher" content="https://www.facebook.com/chaild.official" /> -->

<!-- //Twitter用 -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="http://ryugaku.connect-flow.me/">
<!-- <meta name="twitter:site" content="@CHAILD_official" /> -->
<meta name="twitter:title" content="HANASERU" />
<!-- <meta name="twitter:url" content="https://twitter.com/CHAILD_official" /> -->
<meta name="twitter:description" content="人生を変えるフィリピン留学。完全無料の留学エージェント「HANASERU」" />
<meta name="twitter:image" content="http://ryugaku.connect-flow.me/img/hanaseru_ogp_1200.jp" />

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- <link rel="shortcut icon" href="..images/hanaseru.png" size="16×16"> -->
<%= favicon_link_tag('hanaseru.png') %>
<!-- <link rel="apple-touch-icon" sizes="128x128" href="..images/hanaseru.png"> -->
<%= favicon_link_tag('hanaseru.png',
                     {:rel => 'apple-touch-icon',
                      :sizes => '180x180',
                      :type => 'image/png'}) %>
<!-- custom_cssのCSS読み込み -->
<%= stylesheet_link_tag :index %>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<title>HANASERU</title>
<meta name="keywords" content="留学,HANASERU,フィリピン,フィリピン留学,セブ,バギオ">
<meta name="description" content="人生を変えるフィリピン留学。完全無料の留学エージェント「HANASERU」">
<meta name="og:keywords" content="留学,HANASERU,フィリピン,フィリピン留学,セブ,バギオ">
<meta name="og:description" content="人生を変えるフィリピン留学。完全無料の留学エージェント「HANASERU」">

app/views/layouts/_header.html.erb
<!-- ====================navbar==================== -->
<nav class="navbar navbar-light fixed-top">
  <a class="navbar-brand" href="#top">
    <p class="sub-title">話せるにコミットした留学エージェント</p>
    <%= image_tag("hanaseru_logo.png", :alt => "ブランド", :height => "40") %>
  </a>
  <div id="Navber">
    <a class="btn btn-success badge-pill nav-link" onclick="gtag('event', 'click', {'event_category': 'line','event_label': 'header'});" onclick="return gtag_report_conversion('http://line.me/ti/p/%40ukz1853u')" href="http://line.me/ti/p/%40ukz1853u" role="button" target="_blank">LINE見積</a>
    <!-- <a class="btn btn-danger badge-pill nav-link" onclick="gtag('event', 'click', {'event_category': 'contact','event_label': 'navbar'});" onclick="return gtag_report_conversion('http://ryugaku.connect-flow.me/#contact')" href="#contact" role="button">面談予約</a> -->
  </div>
</nav>

app/views/layouts/_read_js.html.erb
<!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
     <!-- <%= analytics_init if Rails.env.production? %> -->
    <title>HANASERU</title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <!-- ====================top==================== -->

    <div id="top" style="background-image:url(<%= asset_path "top.jpg" %>)">
      <div class="transparent">
        <!-- <div class="container-fluid">
          <div class="row">
            <div class="col-md-7" style="padding: 0px;"> -->
              <div class="display-table">
                <div class="top-content">

                  <%= yield %>

                </div>
              </div>
            <!-- </div>
            <div class="col-md-5"></div>
          </div>
        </div> -->
      </div>
    </div>

    <%= render 'layouts/body' %>
    <%= render 'layouts/read_js' %>
  </body>
</html>

app/views/steps/_error_message.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong>入力内容にエラーがあります</strong>
    <ul>
      <% @user.errors.each do |attr, msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<p class="admin-header">Dashboard - edit</p>

<div style="margin: 20px;">
  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %> |
  <%= link_to 'Show', @user %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/users/index.html.erb
<p class="admin-header">Dashboard</p>
<table class="table table-striped"><!--    -->
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>お名前</th>
      <th>目的</th>
      <th>英語レベル</th>
      <th>希望地域</th>
      <th>予算感</th>
      <th>学習タイプ</th>
      <th>学校規模</th>
      <th>日本人の多さ</th>
      <th>メアド</th>
      <th>作成日時</th>
      <!-- <th>更新日時</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.purpose %></td>
        <td><%= user.level %></td>
        <td><%= user.area_preference %></td>
        <td><%= user.school_level %></td>
        <td><%= user.school_type %></td>
        <td><%= user.school_scale %></td>
        <td><%= user.japnum %></td>
        <td><%= user.email %></td>
        <td><%= simple_time(user.created_at) %></td>
        <!-- <td><%= user.updated_at %></td> -->

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p class="admin-header">Dashboard - show</p>
<p id="notice"><%= notice %></p>

<div style="margin: 20px;">
  <ul style="list-style-type: none; padding: 0px;">
    <li><strong>ID : </strong><%= @user.id %></li>
    <li><strong>お名前 : </strong><%= @user.name %></li>
    <li><strong>目的 : </strong><%= @user.purpose %></li>
    <li><strong>英語レベル : </strong><%= @user.level %></li>
    <li><strong>希望地域 : </strong><%= @user.area_preference %></li>
    <li><strong>予算感 : </strong><%= @user.school_level %></li>
    <li><strong>学習タイプ : </strong><%= @user.school_type %></li>
    <li><strong>学校規模 : </strong><%= @user.school_scale %></li>
    <li><strong>日本人の多さ : </strong><%= @user.japnum %></li>
    <li><strong>メールアドレス : </strong><%= @user.email %></li>
    <li><strong>作成日時 : </strong><%= simple_time(@user.created_at) %></li>
  </ul>

  <%= link_to 'Back', users_path %> |
  <%= link_to 'Edit', edit_user_path(@user) %>
</div>